In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
np.set_printoptions(suppress=True)
pd.set_option('display.max_columns', 100)



In [ ]:
data_dir = '../dataset/_embedding/'

data_file = 'esm.npz'
data_file = os.path.join(data_dir, data_file)
prot_emb = np.load(data_file ,allow_pickle=True)
prot_emb = prot_emb['esm'][()]

data_file = 'dnabert.npz'
data_file = os.path.join(data_dir, data_file)
dna_emb = np.load(data_file,allow_pickle=True)
dna_emb = dna_emb['dnabert'][()]

data_file = 'dnabert_398_1104_622.npz'
data_file = os.path.join(data_dir, data_file)
dna_emb_sup = np.load(data_file,allow_pickle=True)
dna_emb_sup = dna_emb_sup['dnabert'][()]

print(len(dna_emb.keys()))
dna_emb.update(dna_emb_sup)
print(len(dna_emb.keys()))

In [30]:
# prot_fea = np.load('esm.npz',allow_pickle=True)
# prot_fea = prot_fea['esm'][()]
# dna2vec = np.load('dna2vec.npz',allow_pickle=True)
# dna2vec = dna2vec['dna2vec'][()]
# enhancerbert = np.load('enhancerbert.npz',allow_pickle=True)
# enhancerbert = enhancerbert['enhancerbert'][()]
# dnabert = np.load('dnabert.npz',allow_pickle=True)
# dnabert = dnabert['dnabert'][()]

In [35]:
prot_dir = 'prot'
for k, v in tqdm(prot_emb.items()):
    pdir = os.path.join(data_dir, prot_dir, k)
    np.savez(pdir, embedding=v)

nc_dir = 'nc'
for k, v in tqdm(dna_emb.items()):
    pdir = os.path.join(data_dir, nc_dir, k)
    np.savez(pdir, embedding=v)

100%|██████████| 3010/3010 [00:08<00:00, 340.24it/s]


In [4]:
data_dir = '../dataset/_embedding/'
nc_dir = 'nc'
prot_dir = 'prot'

In [10]:
f = os.path.join(data_dir, prot_dir, 'protein_0.npz')
data = np.load(f, allow_pickle=True)
print(data['embedding'].shape)
f = os.path.join(data_dir, nc_dir, 'Double_DNA_398.npz')
data = np.load(f, allow_pickle=True)
print(data['embedding'].shape)

(543, 2560)
(58, 768)


In [2]:
import torch

/home/megvii/anaconda3/envs/paul-py3/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
x = torch.rand(2,2,4,4)
print(x)
m = torch.zeros(2,4, dtype=torch.bool)
m[0, 2:] = True
m[1, -1] = True
print(m)
x.masked_fill(m.unsqueeze(1).unsqueeze(2).to(torch.bool), float("-inf"))

tensor([[[[0.9582, 0.2535, 0.2100, 0.4666],
          [0.4200, 0.3619, 0.4390, 0.6713],
          [0.3976, 0.7727, 0.8344, 0.3008],
          [0.5936, 0.5642, 0.7480, 0.2994]],

         [[0.4449, 0.3568, 0.1383, 0.8400],
          [0.1893, 0.8799, 0.6024, 0.9199],
          [0.4367, 0.9572, 0.0446, 0.1020],
          [0.8079, 0.9061, 0.0587, 0.5517]]],


        [[[0.0456, 0.5209, 0.0256, 0.4412],
          [0.3497, 0.2734, 0.9989, 0.3368],
          [0.0375, 0.5850, 0.8002, 0.6407],
          [0.1234, 0.8672, 0.9744, 0.3217]],

         [[0.7212, 0.6021, 0.6323, 0.1610],
          [0.4791, 0.7481, 0.5966, 0.6056],
          [0.7790, 0.1321, 0.3765, 0.8603],
          [0.8048, 0.4381, 0.7989, 0.0454]]]])
tensor([[False, False,  True,  True],
        [False, False, False,  True]])


tensor([[[[0.9582, 0.2535,   -inf,   -inf],
          [0.4200, 0.3619,   -inf,   -inf],
          [0.3976, 0.7727,   -inf,   -inf],
          [0.5936, 0.5642,   -inf,   -inf]],

         [[0.4449, 0.3568,   -inf,   -inf],
          [0.1893, 0.8799,   -inf,   -inf],
          [0.4367, 0.9572,   -inf,   -inf],
          [0.8079, 0.9061,   -inf,   -inf]]],


        [[[0.0456, 0.5209, 0.0256,   -inf],
          [0.3497, 0.2734, 0.9989,   -inf],
          [0.0375, 0.5850, 0.8002,   -inf],
          [0.1234, 0.8672, 0.9744,   -inf]],

         [[0.7212, 0.6021, 0.6323,   -inf],
          [0.4791, 0.7481, 0.5966,   -inf],
          [0.7790, 0.1321, 0.3765,   -inf],
          [0.8048, 0.4381, 0.7989,   -inf]]]])