In [304]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np

from tqdm import tqdm

# set env
np.set_printoptions(suppress=True)
pd.set_option('display.max_columns', 100)


# seq_dg_230703.txt 是在 0620文件的基础上新增了两列信息；
# dG_ori 列表示原始的dG信息；
# complex_type 列表示复合物类型,wt表示分类为野生型,mut表示分类为突变体,dele则是需要删除的复合物;
# dist_index 列用于索引 dist文件,dist文件在mmseqs文件夹下,共有5个文件,蛋白和四种类型的核酸,
# fident表示距离,范围在0-1之间; 
# 相同的组合,例如 protein_6 和 protein_12之间的dist是相同的,
# 若在核酸的输出文件中检索不到两两之间的相似性，请用0填充,说明其相似性很低;

def convertCsv(df):
    if 'key_nucleic_acids' not in df.columns:
        df.insert(len(df.columns), 'key_nucleic_acids', 'None', allow_duplicates=False)
    for i in range(len(df)):
        row = df.loc[i]
        na_type = row['nucleic_acid_type_new']
        if na_type == 'dsDNA':
            df.loc[i, 'key_nucleic_acids'] = row['newnafea_na_job'].replace('new_DNA', 'Double_DNA')
        elif na_type == 'dsRNA':
            df.loc[i, 'key_nucleic_acids'] = row['newnafea_na_job'].replace('new_RNA', 'Double_RNA')
        elif na_type == 'ssDNA':
            df.loc[i, 'key_nucleic_acids'] = row['na_index'].replace('ssDNA', 'Single_DNA_')
        elif na_type == 'ssRNA':
            df.loc[i, 'key_nucleic_acids'] = row['na_index'].replace('ssRNA', 'Single_RNA_')
    return df


data_root = '../data/_datasets/cluster_res/'

new_ma_f = 'seq_dg_230703.txt'
new_ma_f = os.path.join(data_root, new_ma_f)
new_madf = pd.read_csv(new_ma_f, sep='\t', low_memory=False)
# print(len(new_madf))
# new_madf.head(3)

# if 'key_nucleic_acids' not in new_madf.columns:
#     new_madf.insert(len(new_madf.columns), 'key_nucleic_acids', 'None', allow_duplicates=False)

# for i in range(len(new_madf)):
#     row = new_madf.loc[i]
#     na_type = row['nucleic_acid_type_new']
#     if na_type == 'dsDNA' or na_type == 'dsRNA':
#         double_s_key = row['newnafea_na_job']
#         new_madf.loc[i, 'key_nucleic_acids'] = double_s_key.replace('new', 'Double')
#     elif na_type == 'ssDNA':
#         new_madf.loc[i, 'key_nucleic_acids'] = row['na_index'].replace('ssDNA', 'Single_DNA_')
#     elif na_type == 'ssRNA':
#         new_madf.loc[i, 'key_nucleic_acids'] = row['na_index'].replace('ssRNA', 'Single_RNA_')
new_madf = convertCsv(new_madf)
new_madf.to_csv(os.path.join(data_root, 'seq_dg_v01.txt'), sep='\t', index=False)


wtf = 'wt.tsv'
wtf = os.path.join(data_root, wtf)
wtdf = pd.read_csv(wtf, sep='\t', low_memory=False)
wtdf = convertCsv(wtdf)
wtdf.to_csv(os.path.join(data_root, 'wt_v01.tsv'), sep='\t', index=False)
# The dataset "seq_dg_230702.txt" contains information about dG. 
# The "nucleic_acid_type_new" column represents the four types of nucleic acids. 
# The "dG_ori" column contains the original dG values obtained from the literature. 
# The "complex_type" column indicates whether the complex is of the wild type or mutant type, 
# allowing us to divide the dataset based on this information. 
# By the way,If the value in the "complex_type" column is "dele," 
# it indicates that the complex needs to be removed from the dataset.

# f = os.path.join(data_root, 'seq_dg_230620.txt')
# old_madf = pd.read_csv(f, sep='\t', low_memory=False)
# print(len(old_madf))
# old_madf.head(3)

#230703 
#双链核酸的相似性文件已经修改,是格式的问题,现在能够直接按照 na_index 列进行索引;
#下面是例子;
#dsdnaSim = pd.read_table('/data/sswwkk/Protein_sequence/quanzhe_share/absolute_affinity/date/230702/sim_matrix/dsDNA_ident_matrix.txt',index_col=0)
#seq_dg = pd.read_csv('/data/sswwkk/Protein_sequence/quanzhe_share/absolute_affinity/date/230702/seq_dg_230702.txt',sep='\t')
#seq_dg_dsDNA = seq_dg[seq_dg['nucleic_acid_type_new']=='dsDNA']
#通过以下方式索引
#dsdnaSim.loc['dsdnanew_DNA_3312','dsdnanew_DNA_2549']

# newnafea_na_job：用于索引 2个双链cluster文件 和 2个双链相似度文件
# na_index： 用于索引 2个单链cluster文件 和 2个单链相似度文件
# nucleic_acid_type_new: 核算的种类

def read2df(root, f):
    f = os.path.join(root, f)
    return pd.read_csv(f, sep='\t') # , low_memory=False

def write2csv(root, f, df):
    f = os.path.join(root, f)
    df.to_csv(f, sep='\t', index=False)
    print("write to {}".format(f))
    
pwtc_f = 'protein_wt_cluster.tsv'
ddna_f = 'dsDNA_80_cluster.txt'
drna_f = 'dsRNA_80_cluster.txt'
sdna_f = 'ssDNA_80_cluster.txt'
srna_f = 'ssRNA_80_cluster.txt'

pwtc_df = read2df(data_root, pwtc_f)
ddna_df = read2df(data_root, ddna_f)
drna_df = read2df(data_root, drna_f)
sdna_df = read2df(data_root, sdna_f)
srna_df = read2df(data_root, srna_f)

def convertD(df, cols):
    return df.apply(lambda x: x.replace(
                {'new_DNA': 'Double_DNA', 
                 'new_RNA': 'Double_RNA',
                 'ssDNA': 'Single_DNA_',
                 'ssRNA': 'Single_RNA_'
                },
                regex=True))

changed_cols = ['protein_index', 'cluster_member']

ddna_df = convertD(ddna_df, changed_cols)
drna_df = convertD(drna_df, changed_cols)
sdna_df = convertD(sdna_df, changed_cols)
srna_df = convertD(srna_df, changed_cols)


write2csv(data_root, ddna_f, ddna_df)
write2csv(data_root, drna_f, drna_df)
write2csv(data_root, sdna_f, sdna_df)
write2csv(data_root, srna_f, srna_df)



dir_sim = 'similarity'

sim_ddna_f = 'dsdna_dist_230703.txt'  
sim_drna_f = 'dsrna_dist_230703.txt'
sim_sdna_f = 'ssdna_dist_230703.txt'  
sim_srna_f = 'ssrna_dist_230703.txt'

# sim_ddna_df = pd.read_table(os.path.join(data_root, dir_sim, sim_ddna_f), index_col=0)
# sim_drna_df = pd.read_table(os.path.join(data_root, dir_sim, sim_drna_f), index_col=0)
# sim_sdna_df = pd.read_table(os.path.join(data_root, dir_sim, sim_sdna_f), index_col=0)
# sim_srna_df = pd.read_table(os.path.join(data_root, dir_sim, sim_srna_f), index_col=0)
sim_dir = os.path.join(data_root, dir_sim)

sim_ddna_df = read2df(sim_dir, sim_ddna_f)
sim_drna_df = read2df(sim_dir, sim_drna_f)
sim_sdna_df = read2df(sim_dir, sim_sdna_f)
sim_srna_df = read2df(sim_dir, sim_srna_f)

changed_cols = ['query', 'target']
sim_ddna_df = convertD(sim_ddna_df, changed_cols)
sim_drna_df = convertD(sim_drna_df, changed_cols)
sim_sdna_df = convertD(sim_sdna_df, changed_cols)
sim_srna_df = convertD(sim_srna_df, changed_cols)

write2csv(sim_dir, sim_ddna_f, sim_ddna_df)
write2csv(sim_dir, sim_drna_f, sim_drna_df)
write2csv(sim_dir, sim_sdna_f, sim_sdna_df)
write2csv(sim_dir, sim_srna_f, sim_srna_df)

print('done')

write to ../data/_datasets/cluster_res/dsDNA_80_cluster.txt
write to ../data/_datasets/cluster_res/dsRNA_80_cluster.txt
write to ../data/_datasets/cluster_res/ssDNA_80_cluster.txt
write to ../data/_datasets/cluster_res/ssRNA_80_cluster.txt
write to ../data/_datasets/cluster_res/similarity/dsdna_dist_230703.txt
write to ../data/_datasets/cluster_res/similarity/dsrna_dist_230703.txt
write to ../data/_datasets/cluster_res/similarity/ssdna_dist_230703.txt
write to ../data/_datasets/cluster_res/similarity/ssrna_dist_230703.txt
done


In [377]:
'type_nucleic_acid' in tmp_df.columns

False

In [378]:
tmp_df = pd.read_csv(os.path.join(data_root, 'seq_dg_v01_1.txt'), sep='\t', low_memory=False)
tmp_df.head(5)


complex_id  dataset_id UniProt  \
0           0    pnat_143  P04150   
1           1  pnat_13395  P27694   
2           2  pnat_13396  P27694   
3           3  pnat_14707  Q8RNV8   
4           4  pnat_14714  Q8RNV8   

                                    protein_sequence  \
0  MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...   
1  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
2  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
3  MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   
4  MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   

                                 nucleotide_sequence nucleic_acid_mutation  \
0                                   CGCCTCCGGGAGAGCT                  NONE   
1         CTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCTTCCCT                  NONE   
2  CCCTTCTTTCTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCT...                  NONE   
3                          CGCACGACTTCCCGGAAGAGCACGC                  NONE   
4                          CGCACGACTTCCTGGAAGAGCACGC                  NONE   

  protein_mutation nucleic_acid_type nucleic_acid_type_new        Kd     dG  \
0             WILD             ssDNA                 ssDNA   3.6e-07  -8.79   
1             WILD               DNA                 ssDNA  1.83e-06  -7.83   
2             WILD               DNA                 ssDNA  1.39e-06  -7.99   
3             WILD               DNA                 ssDNA     5e-10 -12.69   
4             WILD               DNA                 ssDNA     5e-10 -12.69   

    pH     Tm                            Method      pmid data_source  \
0  7.5  298.0  Isothermal titration calorimetry  23222642        pnat   
1  7.8  298.0                      Fluorescence  18729380        pnat   
2  7.8  298.0                      Fluorescence  18729380        pnat   
3  8.3  298.0                         Gel shift  21227928        pnat   
4  8.3  298.0                         Gel shift  21227928        pnat   

                                     protein_na_pair  multiple_dg  max_min  \
0  MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...            1      0.0   
1  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...            1      0.0   
2  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...            1      0.0   
3  MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...            1      0.0   
4  MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...            1      0.0   

  max_min_judge  dG_ori pdb_id     len_p1     len_p2 protein_chain na_chain  \
0          good   -8.79   3fyl  A:74,B:76  C:16,D:16       A_1.B_1  C_1.D_1   
1          good   -7.83   1jmc      A:238        B:8           A_1      B_1   
2          good   -7.99   1jmc      A:238        B:8           A_1      B_1   
3          good  -12.69   3imb      A:238    E:9,F:9           A_1  E_1.F_1   
4          good  -12.69   3imb      A:238    E:9,F:9           A_1  E_1.F_1   

  identity_protein_seq identity_na_seq UniProt_type  protein_sequence_len  \
0                  0.1            0.25   Swiss-Prot                   777   
1                 0.39            0.12   Swiss-Prot                   616   
2                 0.39            0.12   Swiss-Prot                   616   
3                  1.0            0.32       TrEMBL                   238   
4                  1.0            0.28       TrEMBL                   238   

  wt_af2_file_download          mo_pdb_chain  \
0                  yes         1m2z_A,6cfn_C   
1                  yes  1fgu_A,1l1o_C,2b29_A   
2                  yes  1fgu_A,1l1o_C,2b29_A   
3                  yes                2q10_A   
4                  yes                2q10_A   

                                            bs_score nucleotide_sequence_one  \
0             0.7293488372093023,0.23546511627906977                    NONE   
1  0.4446617647058823,0.3088235294117647,0.214705...                    NONE   
2  0.4446617647058823,0.3088235294117647,0.214705...                    NONE   
3                                           

In [368]:
# a = np.arange(10).reshape(1,-1)
# mat = np.concatenate([a,a,a,a,a,a,a,a,a], axis=0)
# i = np.array([3,5,7])
# j = np.array([1,2,6,10,11])
# mat[i, j]

# x = np.array([1,2,6,10,11]).reshape(-1, 1)
# x = np.repeat(x, 3, axis=1)
# print(x)
# for i in range(3):
#     x[:,i] = x[:,i] * (i+1)
# print(x)
# x = np.repeat(x, 3, axis=1)
# print(x)

x = np.array([1,2,6,10,11]).reshape(1, -1)
x = np.repeat(x, 3, axis=0)
print(x)
for i in range(3):
    x[i,:] = x[i,:] * (i+1)
print(x)
x = np.repeat(x, 3, axis=0)
print(x)

[[ 1  2  6 10 11]
 [ 1  2  6 10 11]
 [ 1  2  6 10 11]]
[[ 1  2  6 10 11]
 [ 2  4 12 20 22]
 [ 3  6 18 30 33]]
[[ 1  2  6 10 11]
 [ 1  2  6 10 11]
 [ 1  2  6 10 11]
 [ 2  4 12 20 22]
 [ 2  4 12 20 22]
 [ 2  4 12 20 22]
 [ 3  6 18 30 33]
 [ 3  6 18 30 33]
 [ 3  6 18 30 33]]


In [480]:
def addColumnByName(df, col_name, set_front=False, set_str=True):
  pos = 1 if set_front else len(df.columns)
  fill_val = 'None' if set_str else -1
  if col_name not in df.columns:
    df.insert( pos, col_name, fill_val, allow_duplicates=False )
    print('add a new column {} that does not exist'.format(col_name))
  else:
    print('column {} already exists'.format(col_name))
    
def updateColumnNaType(df):
  col_name = 'key_nucleic_acids'
  addColumnByName(df, col_name)
  # for i in range(len(df)):
  #   row = df.loc[i]
  #   na_type = row['nucleic_acid_type_new']
  #   if na_type == 'dsDNA':
  #       df.loc[i, col_name] = row['newnafea_na_job'].replace('new_DNA', 'Double_DNA')
  #   elif na_type == 'dsRNA':
  #       df.loc[i, col_name] = row['newnafea_na_job'].replace('new_RNA', 'Double_RNA')
  #   elif na_type == 'ssDNA':
  #       df.loc[i, col_name] = row['na_index'].replace('ssDNA', 'Single_DNA_')
  #   elif na_type == 'ssRNA':
  #       df.loc[i, col_name] = row['na_index'].replace('ssRNA', 'Single_RNA_')
  replace_values = {'new_DNA' : 'Double_DNA', 'new_RNA' : 'Double_RNA'}
  sst = df['nucleic_acid_type_new'] == 'dsDNA'
  ss = df[sst]['newnafea_na_job'].str.replace(replace_values)
  df.loc[ss.index, 'key_nucleic_acids'] = ss

  sst = df['nucleic_acid_type_new'] == 'dsRNA'
  ss = df[sst]['newnafea_na_job'].str.replace('new_RNA', 'Double_RNA')
  df.loc[ss.index, 'key_nucleic_acids'] = ss

  sst = df['nucleic_acid_type_new'] == 'ssDNA'
  ss = df[sst]['na_index'].str.replace('ssDNA', 'Single_DNA_')
  df.loc[ss.index, 'key_nucleic_acids'] = ss

  sst = df['nucleic_acid_type_new'] == 'ssRNA'
  ss = df[sst]['na_index'].str.replace('ssRNA', 'Single_RNA_')
  df.loc[ss.index, 'key_nucleic_acids'] = ss

  return df

def updateColumnComplex(df):
  col_name = 'key_complex'
  addColumnByName(df, col_name, set_front=True)

  return df

In [499]:
data_root = '../data/_datasets/cluster_res/'
main_f = 'seq_dg_v01_1.txt'


main_f = os.path.join(data_root, main_f)
main_df = pd.read_csv(main_f, sep='\t', low_memory=False)

all_cls_set1 = set(main_df['base_class'].values)
all_cls_set1

{'DDNACluster_359-PCluster_628',
 'SDNACluster_491-PCluster_474',
 'SDNACluster_484-PCluster_444',
 'DDNACluster_123-PCluster_481',
 'SDNACluster_1334-PCluster_356',
 'DDNACluster_527-PCluster_192',
 'DDNACluster_491-PCluster_694',
 'SRNACluster_676-PCluster_81',
 'SDNACluster_1216-PCluster_436',
 'SRNACluster_693-PCluster_348',
 'SRNACluster_82-PCluster_322',
 'SRNACluster_659-PCluster_64',
 'DDNACluster_1073-PCluster_433',
 'SDNACluster_275-PCluster_121',
 'SDNACluster_1440-PCluster_446',
 'SDNACluster_1138-PCluster_531',
 'SRNACluster_464-PCluster_49',
 'DDNACluster_839-PCluster_478',
 'SDNACluster_278-PCluster_400',
 'DDNACluster_410-PCluster_534',
 'SRNACluster_18-PCluster_65',
 'SRNACluster_642-PCluster_336',
 'SDNACluster_1212-PCluster_413',
 'SDNACluster_870-PCluster_122',
 'DDNACluster_763-PCluster_279',
 'DDNACluster_299-PCluster_634',
 'SDNACluster_1286-PCluster_441',
 'SDNACluster_783-PCluster_420',
 'SDNACluster_494-PCluster_610',
 'SDNACluster_326-PCluster_400',
 'SRNAClu

In [484]:
data_root = '../data/_datasets/cluster_res/'
### from_files located in orig_root
orig_root = 'original_files'
### from files
main_f = 'seq_dg_230703.txt'
wt_f = 'wt.tsv'
### save to files
new_main_f = 'seq_dg_v02.txt'
new_wt_f = 'wt_v02.tsv'

main_f = os.path.join(data_root, orig_root, main_f)
main_df = pd.read_csv(main_f, sep='\t', low_memory=False)

wt_f = os.path.join(data_root, orig_root, wt_f)
wt_df = pd.read_csv(wt_f, sep='\t', low_memory=False)

def updateColumnComplex(df):
  col_name = 'key_complex'
  addColumnByName(df, col_name, set_front=True, set_str=False)
  
  curr_id = 0
  for k, subdf in df.groupby(['protein_sequence', 'nucleotide_sequence', 'nucleic_acid_type_new']):
    ss = subdf['exp_id']
    df.loc[ss.index, col_name] = int( ss.values.min() )
    curr_id += 1
  print("totally have {} unique complex".format(curr_id))



main_df.rename(columns={'complex_id': 'exp_id'}, inplace=True)
updateColumnComplex(main_df)
main_df

add a new column key_complex that does not exist
totally have 9062 unique complex


exp_id  key_complex    dataset_id UniProt  \
0           0            0      pnat_143  P04150   
1           1            1    pnat_13395  P27694   
2           2            2    pnat_13396  P27694   
3           3            3    pnat_14707  Q8RNV8   
4           4            4    pnat_14714  Q8RNV8   
...       ...          ...           ...     ...   
17194   17256        17026  pronab_19233  P35259   
17195   17257        17091  pronab_19205  Q8JPY0   
17196   17258        17091  pronab_19207  Q8JPY0   
17197   17259        17093  pronab_19435  Q9UKV8   
17198   17260        17094  pronab_19433  Q9UKV8   

                                        protein_sequence  \
0      MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...   
1      MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
2      MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
3      MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   
4      MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   
...                                                  ...   
17194  MWDSSYMQQVSEGLMTGKVPIDQVFGANPLEKLYKRRKPKGTVGLQ...   
17195  MYNNKLKVCSGPETTGWISEQLMTGKIPVTDIFIDIDNKPDQMEVR...   
17196  MYNNKLKVCSGPETTGWISEQLMTGKIPVTDIFIDIDNKPDQMEVR...   
17197  MYSGAGPALAPPAPPPPIQGYAFKPPPRPDFGTSGRTIKLQANFFE...   
17198  MYSGAGPALAPPAPPPPIQGYAFKPPPRPDFGTSGRTIKLQANFFE...   

                                     nucleotide_sequence  \
0                                       CGCCTCCGGGAGAGCT   
1             CTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCTTCCCT   
2      CCCTTCTTTCTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCT...   
3                              CGCACGACTTCCCGGAAGAGCACGC   
4                              CGCACGACTTCCTGGAAGAGCACGC   
...                                                  ...   
17194                          GACACCUGAUUC|GAAUCAGGUGUC   
17195              AGAAGGAGGGAGGGAGGA|UCCUCCCUCCCUCCUUCU   
17196              AGAAGGAGGGAGGGAGGA|UCCUCCCUCCCUCCUUCU   
17197   UGGAGUGUGACAAUGGUGUUUG|CAAACACCAUUUGUACACUCCAAAA   
17198    UGGAGUGUGACAAUGGUGUUUG|UCGCAGAAUCCAGAACACUCCUAA   

      nucleic_acid_mutation protein_mutation nucleic_acid_type  \
0                      NONE             WILD             ssDNA   
1                      NONE             WILD               DNA   
2                      NONE             WILD               DNA   
3                      NONE             WILD               DNA   
4                      NONE             WILD               DNA   
...                     ...              ...               ...   
17194                  wild             WILD               RNA   
17195                  wild             WILD               RNA   
17196                  wild             WILD               RNA   
17197                  wild             WILD               RNA   
17198                  wild             WILD               RNA   

      nucleic_acid_type_new        Kd      dG   pH     Tm  \
0                     ssDNA   3.6e-07  -8.790  7.5  298.0   
1                     ssDNA  1.83e-06  -7.830  7.8  298.0   
2                     ssDNA  1.39e-06  -7.990  7.8  298.0   
3                     ssDNA     5e-10 -12.690  8.3  298.0   
4                     ssDNA     5e-10 -12.690  8.3  298.0   
...                     ...       ...     ...  ...    ...   
17194                 dsRNA   9.9e-06  -7.710  8.0  298.0   
17195                 dsRNA     3e-07  -8.235  8.0  298.0   
17196                 dsRNA   2.8e-06  -8.235  8.0  298.0   
17197                 dsRNA   3.1e-10 -12.970  8.0  298.0   
17198                 dsRNA   1.6e-10 -13.360  8.0  298.0   

                                 Method      pmid data_source  \
0      Isothermal titration calorimetry  23222642        pnat   
1                          Fluorescence  18729380        pnat   
2                          Fluorescence  18729380        pnat   
3                             Gel shift  21227928        pnat   
4                             Gel shift  21227928        pnat   
...                     

In [488]:
####### check

data_root = '../data/_datasets/cluster_res/'

main_f = 'seq_dg_v02.txt'
wt_f = 'wt_v02.tsv'

main_f = os.path.join(data_root, main_f)
main_df = pd.read_csv(main_f, sep='\t', low_memory=False)

wt_f = os.path.join(data_root, wt_f)
wt_df = pd.read_csv(wt_f, sep='\t', low_memory=False)

In [493]:
main_df[main_df['key_complex'] == 218]

exp_id  key_complex    dataset_id UniProt  \
217      218          218    pnat_16383  P10074   
976      982          218  pronab_16120  P10074   
2224    2236          218    pnat_16391  P10074   
2225    2237          218    pnat_16392  P10074   
2226    2238          218    pnat_16393  P10074   
2227    2239          218    pnat_16394  P10074   
2228    2240          218    pnat_16395  P10074   
2229    2241          218    pnat_16396  P10074   
2230    2242          218    pnat_16397  P10074   

                                       protein_sequence nucleotide_sequence  \
217   MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
976   MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2224  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2225  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2226  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2227  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2228  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2229  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   
2230  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...              TTAGGG   

     nucleic_acid_mutation protein_mutation nucleic_acid_type  \
217                   NONE             WILD               DNA   
976                   wild             WILD               DNA   
2224                  NONE             WILD               DNA   
2225                  NONE             WILD               DNA   
2226                  NONE             WILD               DNA   
2227                  NONE             WILD               DNA   
2228                  NONE             WILD               DNA   
2229                  NONE             WILD               DNA   
2230                  NONE             WILD               DNA   

     nucleic_acid_type_new       Kd    dG   pH     Tm        Method      pmid  \
217                  ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
976                  ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2224                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2225                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2226                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2227                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2228                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2229                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   
2230                 ssDNA  1.7e-07 -9.08  7.5  293.0  Fluorescence  29134956   

     data_source                                    protein_na_pair  \
217         pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
976       pronab  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2224        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2225        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2226        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2227        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2228        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2229        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   
2230        pnat  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   

      multiple_dg  max_min max_min_judge  dG_ori pdb_id     len_p1     len_p2  \
217             9      0.0       lower_1   -9.08   5yj3  C:70,D:66  A:18,B:18   
976             9      0.0       lower_1   -9.08   5yj3  C:70,D:66  A:18,B:18   
2224            9      0.0       lower_1   -9.08   NONE       NONE       NONE   
2225            9      0.0       lower_1   -9.08   NONE       NONE       NONE   
2226            9      0.0       lower_1   -9.08   NONE       NONE       NONE   
2227            9      0.0       lower_1   -9

In [494]:
wt_df[wt_df['key_complex'] == 218]

UniProt  key_complex protein_index  na_index mutation_type  \
105  P10074          218   protein_233  ssDNA118          WILD   

    protein_mutation                                   protein_sequence  \
105             WILD  MDGSFVQHSVRVLQELNKQREKGQYCDATLDVGGLVFKAHWSVLAC...   

    nucleotide_sequence nucleic_acid_type_new    dG newnafea_na_job  na_jobid  \
105              TTAGGG                 ssDNA -9.08     new_DNA_118  DNA_0355   

    protein_na_pair_index  exp_id key_nucleic_acids  
105  protein_233_ssDNA118     218    Single_DNA_118

In [495]:
clsPair2dist_f = os.path.join(data_root, 'output_v01.npz')
if os.path.exists(clsPair2dist_f):
  clsPair2dist_npzData = np.load(clsPair2dist_f, allow_pickle=True)
  map_cls_pair2dist = clsPair2dist_npzData['map_cls_pair2dist'].item()
  print('similarity data of cluster pair exists, read: {}'.format(clsPair2dist_f))

similarity data of cluster pair exists, read: ../data/_datasets/cluster_res/output_v01.npz


In [510]:
import sys
np.set_printoptions(threshold=sys.maxsize)
data_root = '../data/_datasets/cluster_res/'
main_f = 'seq_dg_v02_1.txt'

main_f = os.path.join(data_root, main_f)
main_df = pd.read_csv(main_f, sep='\t', low_memory=False)

# ks=np.unique(main_df['base_class'].values)
# len(ks)

4227

In [512]:
other_root = '../data/pri_data/'

train_df = pd.read_csv( os.path.join(other_root, 'train', 'train.csv'), sep='\t', low_memory=False)
test_df = pd.read_csv( os.path.join(other_root, 'test', 'test.csv'), sep='\t', low_memory=False)

In [518]:
uid2all = dict()
for k, subdf in main_df.groupby('key_complex'):
    uid2all[k] = subdf['exp_id'].values

In [521]:
n_uniq = 0
n_same = 0
nxx = 0
nyy = 0
for k, subdf in main_df.groupby('key_complex'):
    m = test_df['complex_id'].isin(subdf['exp_id'].values)
    ss = test_df['complex_id'][m]
    cids = ss.values
    if len(cids) > 0:
        if len(subdf['exp_id'].values) == 1:
            n_uniq += 1
        else:
            n_same += 1
            n = len(subdf['exp_id'].values) - len(cids)
            if n == 0:
                nyy += 1
            nxx += n
n_uniq, n_same, nxx, nyy

(1358, 2479, 5402, 0)