In [159]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
np.set_printoptions(suppress=True)

# data_dir = '../data/_datasets/'
# data_file = 'seq_dg_mut_final_230629.tsv'
# data_file = os.path.join(data_dir, data_file)
# df = pd.read_csv(data_file, sep='\t')
# print(len(df))
# df.head(3)

data_dir = '../data/_datasets/'
data_file = 'seq_dg_wt_final_230629.tsv'
data_file = os.path.join(data_dir, data_file)
wt_df = pd.read_csv(data_file, sep='\t')
print(len(wt_df))
wt_df.head(3)


4846


UniProt protein_index na_index mutation_type protein_mutation  \
0  P04150     protein_6   ssDNA0          WILD             WILD   
1  P27694    protein_12   ssDNA1          WILD             WILD   
2  P27694    protein_12   ssDNA2          WILD             WILD   

                                    protein_sequence  \
0  MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...   
1  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
2  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   

                                 nucleotide_sequence nucleic_acid_type_new  \
0                                   CGCCTCCGGGAGAGCT                 ssDNA   
1         CTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCTTCCCT                 ssDNA   
2  CCCTTCTTTCTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCT...                 ssDNA   

     dG newnafea_na_job  na_jobid protein_na_pair_index  complex_id  
0 -8.79       new_DNA_0  DNA_0022      protein_6_ssDNA0           0  
1 -7.83       new_DNA_1  DNA_0225     protein_12_ssDNA1           1  
2 -7.99       new_DNA_2  DNA_0226     protein_12_ssDNA2           2

In [7]:
#### load main dataset

data_dir = '../data/_datasets/'
data_file = 'seq_dg_cluster_final_230607_v2.csv'
data_file = os.path.join(data_dir, data_file)
main_df = pd.read_csv(data_file, sep='\t')
main_df.head(3)

<ipython-input-7-97644075a94b>:4: DtypeWarning: Columns (8,11,13,35,36,37,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  main_df = pd.read_csv(data_file, sep='\t')


complex_id  dataset_id UniProt  \
0           0    pnat_143  P04150   
1           1  pnat_13395  P27694   
2           2  pnat_13396  P27694   

                                    protein_sequence  \
0  MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...   
1  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
2  MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   

                                 nucleotide_sequence protein_mutation  \
0                                   CGCCTCCGGGAGAGCT             wild   
1         CTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCTTCCCT             wild   
2  CCCTTCTTTCTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCT...             wild   

  nucleic_acid_type nucleic_acid_type_new        Kd    dG  ...  \
0             ssDNA                 ssDNA   3.6e-07 -8.79  ...   
1               DNA                 ssDNA  1.83e-06 -7.83  ...   
2               DNA                 ssDNA  1.39e-06 -7.99  ...   

  cluster_na_50_index cluster_na_50_number cluster_na_50_member  \
0        Cluster_1008                    1               ssDNA0   
1        Cluster_1009                    2        ssDNA1,ssDNA2   
2        Cluster_1009                    2        ssDNA1,ssDNA2   

  protein_na_pair_index                     protein_50_na_50  \
0      protein_6_ssDNA0                     protein_6_ssDNA0   
1     protein_12_ssDNA1  protein_12_ssDNA1,protein_12_ssDNA2   
2     protein_12_ssDNA2  protein_12_ssDNA1,protein_12_ssDNA2   

  protein_50_na_50_number  cluster_protein_na_pair_index  \
0                       1                 cluster_pair_0   
1                       2                 cluster_pair_1   
2                       2                 cluster_pair_1   

   dataset_id_pdb_id_protein_index    protein_species  na_jobid  
0          pnat_143_3fyl_protein_6  Rattus norvegicus  DNA_0022  
1       pnat_13395_1jmc_protein_12       Homo sapiens  DNA_0225  
2       pnat_13396_1jmc_protein_12       Homo sapiens  DNA_0226  

[3 rows x 56 columns]

In [ ]:
#### to check if dataset is valid

for i in range(len(wt_df)):
    cid = wt_df.loc[i]['complex_id']
    # wt_df.loc[i]['protein_sequence']
    # wt_df.loc[i]['nucleotide_sequence']
    m_row = main_df.loc[main_df['complex_id'] == cid].iloc[0]
    if m_row['protein_sequence'] != wt_df.loc[i]['protein_sequence'] \
        or m_row['nucleotide_sequence'] != wt_df.loc[i]['nucleotide_sequence']:
        print(cid)

In [66]:
list_rows = []
for i in range(len(wt_df)):
    cid = wt_df.loc[i]['complex_id']
    row_df = main_df.loc[main_df['complex_id'] == cid]
    list_rows.append(row_df)
new_df = pd.concat(list_rows, ignore_index=True)

data_dir = '../data/_datasets/'
data_file = 'wt_complext.csv'
data_file = os.path.join(data_dir, data_file)
# new_df.to_csv(data_file, index=False, sep='\t')

new_wt_df = pd.read_csv(data_file, sep='\t')
new_wt_df

complex_id    dataset_id UniProt  \
0              0      pnat_143  P04150   
1              1    pnat_13395  P27694   
2              2    pnat_13396  P27694   
3              3    pnat_14707  Q8RNV8   
4              4    pnat_14714  Q8RNV8   
...          ...           ...     ...   
4841        4466  pronab_19137  Q12158   
4842       10518   pronab_2121  P01100   
4843       10639  pronab_15718  Q15583   
4844       14698  pronab_16800  P53762   
4845        9061  pronab_19963  P07649   

                                       protein_sequence  \
0     MDSKESLTPGREENPSSVLAQERGDVMDFYKTLRGGATVKVSASSP...   
1     MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
2     MVGQLSEGAIAAIMQKGDTNIKPILQVINIRPITTGNSPPRYRLLM...   
3     MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   
4     MKIWSKEEVVNKLHEIKNKGYLSVPTDMFRTDDGVVGQILERQFGV...   
...                                                 ...   
4841  MVTENPQRLTVLRLATNKGPLAQIWLASNMSNIPRGSVIQTHIAES...   
4842  MMFSGFNADYEASSSRCSSASPAGDSLSYYHSPADSFSSMGSPVNA...   
4843  MVLAQSRVSAGVGSPHCSGSGGGGSDSFPWPASHPGNPQCSFSTAF...   
4844  MAATTANPEMTSDVPSLGPTIASGNPGPGIQGGGAVVQRAIKRRSG...   
4845  MSDQQQPPVYKIALGIEYDGSKYYGWQRQNEVRSVQEKLEKALSQV...   

                                    nucleotide_sequence protein_mutation  \
0                                      CGCCTCCGGGAGAGCT             wild   
1            CTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCTTCCCT             wild   
2     CCCTTCTTTCTCTTCCCCCTCTCCTTCTTGCGCTCTTCCTTCCCCT...             wild   
3                             CGCACGACTTCCCGGAAGAGCACGC             wild   
4                             CGCACGACTTCCTGGAAGAGCACGC             wild   
...                                                 ...              ...   
4841                   TGGAAGCCTTTTCAAGGAAACGAAAGTGAACT     K363E, R364E   
4842                    CGCGTGACTCACCCC|GGGGTGAGTCACGCG            K153A   
4843                  ATTGACAGCTGTCAAT|ATTGACAGCTGTCAAT     R167A, R168A   
4844        GGCTGCGTACGTGCGGGTCGT|ACGACCCGCACGTACGCAGCC             H94A   
4845                                      ACCUUGAGGUGGU             R58A   

     nucleic_acid_type nucleic_acid_type_new        Kd     dG  ...  \
0                ssDNA                 ssDNA   3.6e-07  -8.79  ...   
1                  DNA                 ssDNA  1.83e-06  -7.83  ...   
2                  DNA                 ssDNA  1.39e-06  -7.99  ...   
3                  DNA                 ssDNA     5e-10 -12.69  ...   
4                  DNA                 ssDNA     5e-10 -12.69  ...   
...                ...                   ...       ...    ...  ...   
4841               DNA                 ssDNA   1.9e-06  -7.80  ...   
4842               DNA                 dsDNA   2.6e-07  -8.98  ...   
4843               DNA                 dsDNA  3.89e-07  -8.59  ...   
4844               DNA                 dsDNA   1.1e-07  -9.49  ...   
4845               RNA                 ssRNA   6.2e-07  -8.46  ...   

            cluster_na_50_index cluster_na_50_number cluster_na_50_member  \
0                  Cluster_1008                    1               ssDNA0   
1                  Cluster_1009                    2        ssDNA1,ssDNA2   
2                  Cluster_1009                    2        ssDNA1,ssDNA2   
3                  Cluster_1010                    1               ssDNA3   
4                  Cluster_1011                    1               ssDNA4   
...                         ...                  ...                  ...   
4841               Cluster_1266                    1             ssDNA274   
4842  Cluster_2239,Cluster_2240                    1             dsDNA296   
4843  Cluster_2271,Cluster_2271                    1             dsDNA312   
4844  Cluster_1002,Cluster_1003                    1             dsDNA225   
4845                Cluster_624                    1             ssRNA898   

      protein_na_pair_index  \
0          protein_6_ssDNA0   
1         protein_12_ssDNA1   
2         protein_12

In [108]:
all_lens = []
for i in range(len(new_wt_df)):
    prot_seq = new_wt_df.loc[i]['protein_sequence']
    all_lens.append(len(prot_seq))
all_lens = np.array(all_lens)
all_lens.max()

1922

In [118]:
data_dir = '../data/_datasets/'
data_file = 'wt_complext.csv'
data_file = os.path.join(data_dir, data_file)
# new_df.to_csv(data_file, index=False, sep='\t')

new_wt_df = pd.read_csv(data_file, sep='\t')
len_data = len(new_wt_df)

shuf_ids = np.random.permutation(len_data)
num_train = np.floor(0.8 * len_data).astype(np.int32)
num_test = len_data - num_train
print("train size = {}, test size = {}".format(num_train, num_test))


NUM_CV = 5

list_test_indices = []
list_train_indices = []

for i in range(NUM_CV):
    mask = np.zeros_like(shuf_ids).astype(np.bool_)
    ibeg = i * num_test
    iend = min( (i+1) * num_test, len_data)
    print("mark test set from index {} to index {}".format(ibeg, iend))
    
    mask[ibeg : iend] = True
    inv_mask = np.invert(mask)
    
    test_shf_ids = shuf_ids[mask]
    train_shf_ids = shuf_ids[inv_mask]
    
    print("train size = {}, test size = {}".format(len(train_shf_ids), len(test_shf_ids)))
    
    list_test_indices.append(test_shf_ids)
    list_train_indices.append(train_shf_ids)


def create_dir(path):
    if not os.path.exists(path):
        print("to create path, {}".format(path))
        os.makedirs(path)
    else:
        print("already existed path, {}".format(path))

cv5_data_dir = '../data/cv5_data/'

for i in range(NUM_CV):
    cv5_sub_dir = 'cv{}'.format(i)
    cv5_train_dir = os.path.join(cv5_data_dir, cv5_sub_dir, 'train')
    cv5_test_dir = os.path.join(cv5_data_dir, cv5_sub_dir, 'test')
    create_dir(cv5_train_dir)
    create_dir(cv5_test_dir)
    
    test_inds, train_inds = list_test_indices[i], list_train_indices[i]
    
    temp_test_df = new_wt_df.loc[test_inds]
    temp_train_df = new_wt_df.loc[train_inds]  
    print("train size = {}, test size = {}".format(len(temp_train_df), len(temp_test_df)))
    
    test_fpath = os.path.join(cv5_test_dir, 'data.csv')
    train_fpath = os.path.join(cv5_train_dir, 'data.csv')
    
    temp_test_df.to_csv(test_fpath, index=False, sep='\t')
    temp_train_df.to_csv(train_fpath, index=False, sep='\t')

    

train size = 3876, test size = 970
mark test set from index 0 to index 970
train size = 3876, test size = 970
mark test set from index 970 to index 1940
train size = 3876, test size = 970
mark test set from index 1940 to index 2910
train size = 3876, test size = 970
mark test set from index 2910 to index 3880
train size = 3876, test size = 970
mark test set from index 3880 to index 4846
train size = 3880, test size = 966
to create path, ../data/cv5_data/cv0/train
to create path, ../data/cv5_data/cv0/test
train size = 3876, test size = 970
to create path, ../data/cv5_data/cv1/train
to create path, ../data/cv5_data/cv1/test
train size = 3876, test size = 970
to create path, ../data/cv5_data/cv2/train
to create path, ../data/cv5_data/cv2/test
train size = 3876, test size = 970
to create path, ../data/cv5_data/cv3/train
to create path, ../data/cv5_data/cv3/test
train size = 3876, test size = 970
to create path, ../data/cv5_data/cv4/train
to create path, ../data/cv5_data/cv4/test
train size

In [162]:
train_df = pd.read_csv(train_fpath, sep='\t')
labels = train_df['dG'].values

intervals = np.arange(0, -30, -2).astype(np.float32)
inds_groups = []
for i in range(intervals.shape[0]-1):
    m = np.logical_and(labels > intervals[i], labels <= intervals[i-1])
    inds = np.where(m)[0]

    inds_groups.append(inds)

test_df = pd.read_csv(test_fpath, sep='\t')
labels = test_df['dG'].values

test_inds_groups = []
for i in range(intervals.shape[0]-1):
    m = np.logical_and(labels > intervals[i], labels <= intervals[i-1])
    inds = np.where(m)[0]

    test_inds_groups.append(inds)

In [165]:
train_dist = np.array([len(x) for x in inds_groups])
test_dist = np.array([len(x) for x in test_inds_groups])

# train_dist = train_dist / np.sum(train_dist)
# test_dist = test_dist / np.sum(test_dist)
train_dist

array([   0,    7,   16,  151,  648, 1383, 1195,  408,   58,   12,    0,
          1,    0,    1])

In [167]:
intervals

array([  0.,  -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18., -20.,
       -22., -24., -26., -28.], dtype=float32)

In [166]:
test_dist

array([  0,   2,   2,  30, 147, 345, 333,  92,  12,   3,   0,   0,   0,
         0])

In [146]:
info = {'loss': 1.1, 'rvalue': 0.2, 'pvalue': 22, 'rrmse': 3.0}
# np.savez('test{:.3f}'.format(0.3124231523452345), info=info)
np.savez('test', info=info)
d = np.load('test.npz', allow_pickle=True)
d['info']

array({'loss': 1.1, 'rvalue': 0.2, 'pvalue': 22, 'rrmse': 3.0},
      dtype=object)